### ISSUE TITLE
I want to give you money

### ISSUE THREAD

**Issue by EwonRael** [trufont/trufont.github.io#10]
It would be nice to be able to donate to this project.

It doesn't have to be more complicated than a https://www.paypal.me/ link.

Make it happen!

**Comment by pathumego** [comment]
@adrientetar any plans to enable this?

**Comment by adrientetar** [comment]
No, I wouldn't have much use for it either way.

**Comment by davelab6** [comment]
You can donate to the libre font fund at tug.org which I will direct for
use on trufont after it's 1.0 release
