### ISSUE TITLE
Use logotype on homepage

### ISSUE THREAD

**Issue by davelab6** [trufont/trufont.github.io#2]
While https://github.com/trufont/trufont.github.io/blob/master/img/app.png is used on the homepage, https://github.com/trufont/trufont.github.io/blob/master/img/trufont.svg is not. It would be great to add the logotype to the page, perhaps as a footer on the current small page? :)

**Comment by adrientetar** [comment]
Wordmark and logo are two strong brand elements and as such they are mutually exclusive. The emphasis is put on the logo. The wordmark can be used where there is a need to emphase on the name e.g. sponsorship/media kit.

The logo is also more recent, the wordmark is what we did while the logo was in the works.

**Comment by davelab6** [comment]
I think its very bad practice to have the wordmark link to the site, and
then not see the workmark on the site to confirm the user is in the right
place.

**Comment by adrientetar** [comment]
I know but we did what we could to get something in time.
